server:
  port: ${INTEGRATION_MANAGER_SERVER_PORT:8082}
  shutdown: graceful
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        generate_statistics: false

  datasource:
    hikari:
      initialization-fail-timeout: 0
    url: ${ADENDO_DATABASE_URL}
    username: ${ADENDO_DATABASE_USERNAME}
    password: ${ADENDO_DATABASE_PASSWORD}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      location: './temp'
  application:
    name: processamento-planilhas
  main:
    banner-mode: off
   # lazy-initialization: true
  threads:
    virtual:
      enabled: true


springdoc:
  api-docs:
    path: /api-docs
    resolve-extensions-properties: true
  override-with-generic-response: false
  paths-to-exclude: /**/api-docs,/swagger-resources/**
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include:  health
      base-path: '/actuator'